development:
  adapter: postgresql
  database: sample_dev
  host: localhost

test:
  adapter: postgresql
  database: sample_test
  host: localhost

production:
  adapter: postgresql
  database: sample_live
  host: localhost
